const MatchesActionTypes = {
  FETCH_MATCHES_START: "FETCH_MATCHES_START",
  FETCH_MATCHES_SUCCESS: "FETCH_MATCHES_SUCCESS",
  FETCH_MATCHES_FAILURE: "FETCH_MATCHES_FAILURE",
  REMOVE_MATCH_START: "REMOVE_MATCH_START",
  REMOVE_MATCH_SUCCESS: "REMOVE_MATCH_SUCCESS",
  REMOVE_MATCH_FAILURE: "REMOVE_MATCH_FAILURE",
};

export default MatchesActionTypes;
