const PlayersActionTypes = {
  FETCH_PLAYERS_START: "FETCH_PLAYERS_START",
  FETCH_PLAYERS_SUCCESS: "FETCH_PLAYERS_SUCCESS",
  FETCH_PLAYERS_FAILURE: "FETCH_PLAYERS_FAILURE",
  DELETE_PLAYER_START: "DELETE_PLAYER_START",
  DELETE_PLAYER_SUCCESS: "DELETE_PLAYER_SUCCESS",
  DELETE_PLAYER_FAILURE: "DELETE_PLAYER_FAILURE",
  FETCH_CURRENT_TEAM_START: "FETCH_CURRENT_TEAM_START",
  FETCH_CURRENT_TEAM_SUCCESS: "FETCH_CURRENT_TEAM_SUCCESS",
  FETCH_CURRENT_TEAM_FAILURE: "FETCH_CURRENT_TEAM_FAILURE",
  DELETE_PLAYER_FROM_OTHER_TEAM_START: "DELETE_PLAYER_FROM_OTHER_TEAM_START",
  DELETE_PLAYER_FROM_OTHER_TEAM_SUCCESS:
    "DELETE_PLAYER_FROM_OTHER_TEAM_SUCCESS",
  DELETE_PLAYER_FROM_OTHER_TEAM_FAILURE:
    "DELETE_PLAYER_FROM_OTHER_TEAM_FAILURE",
};

export default PlayersActionTypes;
