const TeamsActionTypes = {
  FETCH_TEAMS_START: "FETCH_TEAMS_START",
  FETCH_TEAMS_SUCCESS: "FETCH_TEAMS_SUCCESS",
  FETCH_TEAMS_FAILURE: "FETCH_TEAMS_FAILURE",
  DELETE_TEAM_START: "DELETE_TEAM_START",
  DELETE_TEAM_SUCCESS: "DELETE_TEAM_SUCCESS",
  DELETE_TEAM_FAILURE: "DELETE_TEAM_FAILURE",
};

export default TeamsActionTypes;
